version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app-accounts-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-sraswznf2zk7"
s3_prefix = "sam-app-accounts-stack"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
